### ISSUE TITLE
add quantization to CityJSON files

### ISSUE THREAD

**Issue by hugoledoux** [FHOOEAIST/geofiles#28]
First, very interesting work, thanks for doing this!

I noticed that the CityJSON files are not created with the `"transform"` (https://www.cityjson.org/specs/1.0.3/#transform-object) and that would save ~10%. If you use cjio you can use the compress operator (and specify the number of digits to keep, default is 3).

By the way, CityJSON v1.1 will be released later this month, and with that version the `"transform"` will become mandatory.

**Comment by cpraschl** [comment]
Thank you very much for your feedback and the information regarding the `transform object`. We will extend our framework to also support transform information for CityJSON as soon v1.1. is released :)

 Is there any unit defined for the translation? Is it metric? Unfortunately, I could not find anything about this in the provided specs.

**Comment by hugoledoux** [comment]
No units prescribed. The transform could be anything you want really. 

But in practice to compress cjio will take the minx/miny of the dataset and take a certain number of digits (3 is the default, so millimetre if meters are the unit; this can be changed). 

v1.1 will be released December 1 btw.
